spring.application.name=journalAppNew

spring.data.mongodb.uri=mongodb+srv://tegocharlie_db_user:Realme@cluster0.kwg7s1r.mongodb.net/journalDB?appName=Cluster0

spring.data.mongodb.auto-index-creation=true